version: '2'

services:
  db:
    image: mongo:3.5

  redis:
    image: redis:3

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    entrypoint: ["/entrypoint.sh"]
    command: ["uwsgi", "--http", "0.0.0.0:5000", "--uid", "web", "--master", "--module", "app:app", "--processes", "1", "--threads", "8"]
    ports:
      - "5000:5000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    entrypoint: ["/entrypoint.sh"]
    command: ["celery", "worker", "-l", "info", "-A", "worker.tasks"]

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    entrypoint: ["/entrypoint.sh"]
    command: ["celery", "-l", "info", "-A", "scheduler.schedulers", "-S", "scheduler.schedulers.MongoScheduler", "beat"]