db:
  image: mongo:latest
  environment:
    - MONGO_PWD=mypass

redis:
  image: redis:latest
  environment:
    - REDIS_PWD=mypass

web:
  build: .
  dockerfile: Dockerfile.web
  entrypoint: ["/entrypoint.sh"]
  command: ["python", "app.py"]
  ports:
    - "5000:5000"
  links:
    - db:db
    - redis:redis

worker:
  build: .
  dockerfile: Dockerfile.worker
  entrypoint: ["/entrypoint.sh"]
  command: ["celery", "worker", "-l", "info", "-A", "worker.tasks"]
  links:
    - db:db
    - redis:redis

crawler:
  build: .
  dockerfile: Dockerfile.crawler
  entrypoint: ["/entrypoint.sh"]
  command: ["celery", "worker", "-l", "info", "-A", "crawler.tasks"]
  links:
    - db:db
    - redis:redis