version: '2'

services:
  db:
    image: mongo:latest

  redis:
    image: redis:3.2.2-alpine

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    entrypoint: ["/entrypoint.sh"]
    command: ["uwsgi", "--http", "0.0.0.0:5000", "--uid", "web", "--master", "--module", "app:app", "--processes", "1", "--threads", "8"]
    ports:
      - "5000:5000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    entrypoint: ["/entrypoint.sh"]
    command: ["celery", "worker", "--autoreload", "-l", "info", "-A", "worker.tasks", "-Q", "thugtask"]

  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    entrypoint: ["/entrypoint.sh"]
    command: ["celery", "worker", "--autoreload", "-l", "info", "-A", "crawler.tasks", "-Q", "crawlertask"]


  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    entrypoint: ["/entrypoint.sh"]
    command: ["celery", "-l", "info", "-A", "scheduler.schedulers", "-S", "scheduler.schedulers.CustomMongoScheduler", "beat"]



