version: '2'

services:
  db:
    image: mongo:latest

  redis:
    image: redis:latest

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    entrypoint: ["/entrypoint.sh"]
    command: ["uwsgi", "--http", "0.0.0.0:5000", "--uid", "web", "--master", "--module", "app:app", "--processes", "1", "--threads", "8"]
    ports:
      - "5000:5000"
    volumes:
      - .:/opt/project

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    entrypoint: ["/entrypoint.sh"]
    command: ["celery", "worker", "-l", "DEBUG", "-A", "worker.tasks"]
    volumes:
      - .:/opt/project



