db:
  image: mongo:latest
  environment:
    - MONGO_PWD=mypass

redis:
  image: redis:3.2.2-alpine
  environment:
    - REDIS_PWD=mypass

web:
  build: .
  dockerfile: Dockerfile.web
  entrypoint: ["/entrypoint.sh"]
  command: ["python", "app.py"]
  ports:
    - "5000:5000"
  links:
    - db:db
    - redis:redis

worker:
  build: .
  dockerfile: Dockerfile.worker
  entrypoint: ["/entrypoint.sh"]
  command: ["celery", "worker", "--autoreload", "-l", "DEBUG", "-A", "worker.tasks", "-Q", "thugtask"]
  links:
    - db:db
    - redis:redis

crawler:
  build: .
  dockerfile: Dockerfile.crawler
  entrypoint: ["/entrypoint.sh"]
  command: ["celery", "worker", "--autoreload", "-l", "DEBUG", "-A", "crawler.tasks", "-Q", "crawlertask"]
  links:
    - db:db
    - redis:redis

scheduler:
  build: .
  dockerfile: Dockerfile.scheduler
  entrypoint: ["/entrypoint.sh"]
  command: ["celery", "-l", "DEBUG", "-A", "scheduler.schedulers", "-S", "scheduler.schedulers.CustomMongoScheduler", "beat"]
  links:
    - db:db
    - redis:redis

